<?php

/**
 * @file
 * Contains dragomans.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dragomans_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dragomans module.
    case 'help.page.dragomans_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('dragomans_migrate') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_migration_plugins_alter().
 */
function dragomans_migrate_migration_plugins_alter(&$definitions) {
  $definitions['migrate_csv']['source']['path'] = drupal_get_path('module', 'dragomans_migrate') . $definitions['migrate_csv']['source']['path'];
}

